repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1  # уточните актуальную версию
    hooks:
      - id: gitleaks
        name: gitleaks pre-commit scan
        entry: gitleaks protect --verbose --staged
        language: system
        types: [file]
